# WARNING: This is a work in progress. Don't use this starter workflow yet.
# This is a starter workflow for CI pipelines in the 'cartdotcom' organization.
# For more information about starter workflows, please visit this link:
# https://docs.github.com/en/actions/using-workflows/using-starter-workflows
name: CI

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - 'k8s/**'

jobs:
  ci:
   uses: cartdotcom/unified-deployments/.github/workflows/microservice-ci.yaml
   with:
    # Change this value to match your stack. Possible values are listed below.
    # ['nodejs', 'python', '.NET']
    stack: nodejs