# This is a starter workflow for image vulnerability scanning in the 'cartdotcom' organization.
# All reusable workflows can be found here: https://github.com/cartdotcom/unified-deployments.
# For more information about starter workflows, please visit this link:
# https://docs.github.com/en/actions/using-workflows/using-starter-workflows
name: Scan

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      # Add any paths or globs here that you wish this pipeline to ignore.
      # More information about path ignoring can be found here:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
      - .github/**

jobs:
  scan:
    uses: cartdotcom/unified-deployments/.github/workflows/image-vulnerability-scan.yaml@main
    with:
      dockerfile_directory_path: .